[2025-05-02 16:52:47,839] {processor.py:153} INFO - Started process (PID=2868) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:52:47,839] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:52:47,840] {logging_mixin.py:115} INFO - [2025-05-02 16:52:47,839] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:52:47,847] {logging_mixin.py:115} INFO - [2025-05-02 16:52:47,847] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:52:47,847] {logging_mixin.py:115} INFO - [2025-05-02 16:52:47,847] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:52:47,847] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:52:47,852] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-02 16:53:19,683] {processor.py:153} INFO - Started process (PID=3224) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:19,684] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:53:19,684] {logging_mixin.py:115} INFO - [2025-05-02 16:53:19,684] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:19,700] {logging_mixin.py:115} INFO - [2025-05-02 16:53:19,699] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:53:19,700] {logging_mixin.py:115} INFO - [2025-05-02 16:53:19,700] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:53:19,700] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:19,713] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-05-02 16:53:50,500] {processor.py:153} INFO - Started process (PID=3674) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:50,501] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:53:50,501] {logging_mixin.py:115} INFO - [2025-05-02 16:53:50,501] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:50,509] {logging_mixin.py:115} INFO - [2025-05-02 16:53:50,509] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:53:50,510] {logging_mixin.py:115} INFO - [2025-05-02 16:53:50,510] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:53:50,510] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:53:50,515] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 16:54:21,555] {processor.py:153} INFO - Started process (PID=3806) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:21,555] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:54:21,556] {logging_mixin.py:115} INFO - [2025-05-02 16:54:21,556] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:21,563] {logging_mixin.py:115} INFO - [2025-05-02 16:54:21,563] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:54:21,564] {logging_mixin.py:115} INFO - [2025-05-02 16:54:21,564] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:54:21,564] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:21,569] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 16:54:53,760] {processor.py:153} INFO - Started process (PID=3942) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:53,761] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:54:53,761] {logging_mixin.py:115} INFO - [2025-05-02 16:54:53,761] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:53,769] {logging_mixin.py:115} INFO - [2025-05-02 16:54:53,768] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:54:53,769] {logging_mixin.py:115} INFO - [2025-05-02 16:54:53,769] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:54:53,769] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:54:53,774] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-02 16:55:24,823] {processor.py:153} INFO - Started process (PID=4074) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:24,824] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:55:24,824] {logging_mixin.py:115} INFO - [2025-05-02 16:55:24,824] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:24,836] {logging_mixin.py:115} INFO - [2025-05-02 16:55:24,835] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:55:24,836] {logging_mixin.py:115} INFO - [2025-05-02 16:55:24,836] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:55:24,836] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:24,843] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-05-02 16:55:56,622] {processor.py:153} INFO - Started process (PID=4499) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:56,623] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:55:56,623] {logging_mixin.py:115} INFO - [2025-05-02 16:55:56,623] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:56,632] {logging_mixin.py:115} INFO - [2025-05-02 16:55:56,631] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:55:56,632] {logging_mixin.py:115} INFO - [2025-05-02 16:55:56,632] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:55:56,632] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:55:56,637] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 16:56:27,219] {processor.py:153} INFO - Started process (PID=4631) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:56:27,219] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:56:27,220] {logging_mixin.py:115} INFO - [2025-05-02 16:56:27,219] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:56:27,227] {logging_mixin.py:115} INFO - [2025-05-02 16:56:27,227] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:56:27,227] {logging_mixin.py:115} INFO - [2025-05-02 16:56:27,227] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:56:27,228] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:56:27,233] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 16:57:01,046] {processor.py:153} INFO - Started process (PID=4772) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:01,046] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:57:01,047] {logging_mixin.py:115} INFO - [2025-05-02 16:57:01,047] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:01,054] {logging_mixin.py:115} INFO - [2025-05-02 16:57:01,054] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:57:01,054] {logging_mixin.py:115} INFO - [2025-05-02 16:57:01,054] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:57:01,054] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:01,059] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-02 16:57:32,672] {processor.py:153} INFO - Started process (PID=4912) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:32,673] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:57:32,673] {logging_mixin.py:115} INFO - [2025-05-02 16:57:32,673] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:32,681] {logging_mixin.py:115} INFO - [2025-05-02 16:57:32,681] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:57:32,681] {logging_mixin.py:115} INFO - [2025-05-02 16:57:32,681] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:57:32,681] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:57:32,687] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 16:58:04,037] {processor.py:153} INFO - Started process (PID=5045) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:04,038] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:58:04,038] {logging_mixin.py:115} INFO - [2025-05-02 16:58:04,038] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:04,046] {logging_mixin.py:115} INFO - [2025-05-02 16:58:04,046] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:58:04,046] {logging_mixin.py:115} INFO - [2025-05-02 16:58:04,046] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:58:04,047] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:04,053] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 16:58:35,744] {processor.py:153} INFO - Started process (PID=5179) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:35,744] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:58:35,745] {logging_mixin.py:115} INFO - [2025-05-02 16:58:35,745] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:35,753] {logging_mixin.py:115} INFO - [2025-05-02 16:58:35,753] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:58:35,753] {logging_mixin.py:115} INFO - [2025-05-02 16:58:35,753] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:58:35,753] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:58:35,759] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 16:59:08,430] {processor.py:153} INFO - Started process (PID=5317) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:08,430] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:59:08,431] {logging_mixin.py:115} INFO - [2025-05-02 16:59:08,430] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:08,438] {logging_mixin.py:115} INFO - [2025-05-02 16:59:08,438] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:59:08,438] {logging_mixin.py:115} INFO - [2025-05-02 16:59:08,438] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:59:08,438] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:08,444] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 16:59:40,082] {processor.py:153} INFO - Started process (PID=5448) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:40,083] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 16:59:40,083] {logging_mixin.py:115} INFO - [2025-05-02 16:59:40,083] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:40,091] {logging_mixin.py:115} INFO - [2025-05-02 16:59:40,090] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 16:59:40,091] {logging_mixin.py:115} INFO - [2025-05-02 16:59:40,091] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 16:59:40,091] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 16:59:40,096] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:00:12,568] {processor.py:153} INFO - Started process (PID=5587) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:12,568] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:00:12,569] {logging_mixin.py:115} INFO - [2025-05-02 17:00:12,569] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:12,579] {logging_mixin.py:115} INFO - [2025-05-02 17:00:12,578] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:00:12,579] {logging_mixin.py:115} INFO - [2025-05-02 17:00:12,579] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:00:12,579] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:12,585] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:00:45,313] {processor.py:153} INFO - Started process (PID=5726) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:45,313] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:00:45,314] {logging_mixin.py:115} INFO - [2025-05-02 17:00:45,314] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:45,321] {logging_mixin.py:115} INFO - [2025-05-02 17:00:45,321] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:00:45,321] {logging_mixin.py:115} INFO - [2025-05-02 17:00:45,321] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:00:45,321] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:00:45,327] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:01:18,315] {processor.py:153} INFO - Started process (PID=5865) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:18,316] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:01:18,316] {logging_mixin.py:115} INFO - [2025-05-02 17:01:18,316] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:18,324] {logging_mixin.py:115} INFO - [2025-05-02 17:01:18,324] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:01:18,324] {logging_mixin.py:115} INFO - [2025-05-02 17:01:18,324] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:01:18,324] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:18,330] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:01:50,989] {processor.py:153} INFO - Started process (PID=6006) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:50,990] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:01:50,990] {logging_mixin.py:115} INFO - [2025-05-02 17:01:50,990] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:50,997] {logging_mixin.py:115} INFO - [2025-05-02 17:01:50,997] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:01:50,997] {logging_mixin.py:115} INFO - [2025-05-02 17:01:50,997] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:01:50,997] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:01:51,003] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-02 17:02:22,017] {processor.py:153} INFO - Started process (PID=6146) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:22,018] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:02:22,018] {logging_mixin.py:115} INFO - [2025-05-02 17:02:22,018] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:22,026] {logging_mixin.py:115} INFO - [2025-05-02 17:02:22,026] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:02:22,026] {logging_mixin.py:115} INFO - [2025-05-02 17:02:22,026] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:02:22,026] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:22,032] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:02:52,960] {processor.py:153} INFO - Started process (PID=6276) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:52,961] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:02:52,961] {logging_mixin.py:115} INFO - [2025-05-02 17:02:52,961] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:52,971] {logging_mixin.py:115} INFO - [2025-05-02 17:02:52,971] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:02:52,971] {logging_mixin.py:115} INFO - [2025-05-02 17:02:52,971] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:02:52,971] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:02:52,978] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:03:26,015] {processor.py:153} INFO - Started process (PID=6420) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:26,016] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:03:26,016] {logging_mixin.py:115} INFO - [2025-05-02 17:03:26,016] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:26,024] {logging_mixin.py:115} INFO - [2025-05-02 17:03:26,024] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:03:26,024] {logging_mixin.py:115} INFO - [2025-05-02 17:03:26,024] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:03:26,024] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:26,030] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:03:57,151] {processor.py:153} INFO - Started process (PID=6553) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:57,152] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:03:57,152] {logging_mixin.py:115} INFO - [2025-05-02 17:03:57,152] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:57,160] {logging_mixin.py:115} INFO - [2025-05-02 17:03:57,160] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:03:57,160] {logging_mixin.py:115} INFO - [2025-05-02 17:03:57,160] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:03:57,161] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:03:57,166] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:04:30,822] {processor.py:153} INFO - Started process (PID=6694) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:04:30,823] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:04:30,823] {logging_mixin.py:115} INFO - [2025-05-02 17:04:30,823] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:04:30,831] {logging_mixin.py:115} INFO - [2025-05-02 17:04:30,831] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:04:30,831] {logging_mixin.py:115} INFO - [2025-05-02 17:04:30,831] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:04:30,831] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:04:30,837] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:05:02,054] {processor.py:153} INFO - Started process (PID=6829) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:02,054] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:05:02,055] {logging_mixin.py:115} INFO - [2025-05-02 17:05:02,055] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:02,064] {logging_mixin.py:115} INFO - [2025-05-02 17:05:02,063] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:05:02,064] {logging_mixin.py:115} INFO - [2025-05-02 17:05:02,064] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:05:02,064] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:02,070] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:05:34,726] {processor.py:153} INFO - Started process (PID=6967) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:34,727] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:05:34,727] {logging_mixin.py:115} INFO - [2025-05-02 17:05:34,727] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:34,736] {logging_mixin.py:115} INFO - [2025-05-02 17:05:34,736] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:05:34,736] {logging_mixin.py:115} INFO - [2025-05-02 17:05:34,736] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:05:34,736] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:05:34,742] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:06:06,812] {processor.py:153} INFO - Started process (PID=7102) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:06,812] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:06:06,813] {logging_mixin.py:115} INFO - [2025-05-02 17:06:06,813] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:06,821] {logging_mixin.py:115} INFO - [2025-05-02 17:06:06,821] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:06:06,821] {logging_mixin.py:115} INFO - [2025-05-02 17:06:06,821] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:06:06,821] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:06,827] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:06:39,567] {processor.py:153} INFO - Started process (PID=7240) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:39,568] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:06:39,568] {logging_mixin.py:115} INFO - [2025-05-02 17:06:39,568] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:39,576] {logging_mixin.py:115} INFO - [2025-05-02 17:06:39,576] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:06:39,576] {logging_mixin.py:115} INFO - [2025-05-02 17:06:39,576] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:06:39,576] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:06:39,582] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-02 17:07:11,724] {processor.py:153} INFO - Started process (PID=7382) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:11,725] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:07:11,725] {logging_mixin.py:115} INFO - [2025-05-02 17:07:11,725] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:11,733] {logging_mixin.py:115} INFO - [2025-05-02 17:07:11,733] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:07:11,734] {logging_mixin.py:115} INFO - [2025-05-02 17:07:11,734] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:07:11,734] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:11,740] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:07:45,912] {processor.py:153} INFO - Started process (PID=7520) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:45,913] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:07:45,913] {logging_mixin.py:115} INFO - [2025-05-02 17:07:45,913] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:45,921] {logging_mixin.py:115} INFO - [2025-05-02 17:07:45,921] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:07:45,921] {logging_mixin.py:115} INFO - [2025-05-02 17:07:45,921] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:07:45,921] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:07:45,929] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:08:19,283] {processor.py:153} INFO - Started process (PID=7661) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:19,283] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:08:19,284] {logging_mixin.py:115} INFO - [2025-05-02 17:08:19,284] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:19,292] {logging_mixin.py:115} INFO - [2025-05-02 17:08:19,292] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:08:19,292] {logging_mixin.py:115} INFO - [2025-05-02 17:08:19,292] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:08:19,292] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:19,299] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:08:50,257] {processor.py:153} INFO - Started process (PID=7794) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:50,258] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:08:50,258] {logging_mixin.py:115} INFO - [2025-05-02 17:08:50,258] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:50,266] {logging_mixin.py:115} INFO - [2025-05-02 17:08:50,265] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:08:50,266] {logging_mixin.py:115} INFO - [2025-05-02 17:08:50,266] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:08:50,266] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:08:50,273] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:09:22,857] {processor.py:153} INFO - Started process (PID=7933) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:22,858] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:09:22,858] {logging_mixin.py:115} INFO - [2025-05-02 17:09:22,858] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:22,866] {logging_mixin.py:115} INFO - [2025-05-02 17:09:22,866] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:09:22,866] {logging_mixin.py:115} INFO - [2025-05-02 17:09:22,866] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:09:22,866] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:22,873] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:09:54,714] {processor.py:153} INFO - Started process (PID=8073) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:54,715] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:09:54,715] {logging_mixin.py:115} INFO - [2025-05-02 17:09:54,715] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:54,723] {logging_mixin.py:115} INFO - [2025-05-02 17:09:54,723] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:09:54,723] {logging_mixin.py:115} INFO - [2025-05-02 17:09:54,723] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:09:54,723] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:09:54,730] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:10:29,472] {processor.py:153} INFO - Started process (PID=8219) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:10:29,472] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:10:29,473] {logging_mixin.py:115} INFO - [2025-05-02 17:10:29,473] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:10:29,481] {logging_mixin.py:115} INFO - [2025-05-02 17:10:29,480] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:10:29,481] {logging_mixin.py:115} INFO - [2025-05-02 17:10:29,481] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:10:29,481] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:10:29,488] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:11:00,574] {processor.py:153} INFO - Started process (PID=8359) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:00,574] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:11:00,575] {logging_mixin.py:115} INFO - [2025-05-02 17:11:00,575] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:00,583] {logging_mixin.py:115} INFO - [2025-05-02 17:11:00,583] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:11:00,583] {logging_mixin.py:115} INFO - [2025-05-02 17:11:00,583] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:11:00,584] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:00,591] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:11:33,250] {processor.py:153} INFO - Started process (PID=8503) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:33,250] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:11:33,251] {logging_mixin.py:115} INFO - [2025-05-02 17:11:33,250] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:33,259] {logging_mixin.py:115} INFO - [2025-05-02 17:11:33,259] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:11:33,259] {logging_mixin.py:115} INFO - [2025-05-02 17:11:33,259] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:11:33,259] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:11:33,267] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:12:05,536] {processor.py:153} INFO - Started process (PID=8648) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:05,537] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:12:05,537] {logging_mixin.py:115} INFO - [2025-05-02 17:12:05,537] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:05,545] {logging_mixin.py:115} INFO - [2025-05-02 17:12:05,545] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:12:05,545] {logging_mixin.py:115} INFO - [2025-05-02 17:12:05,545] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:12:05,545] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:05,552] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:12:37,297] {processor.py:153} INFO - Started process (PID=8783) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:37,298] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:12:37,298] {logging_mixin.py:115} INFO - [2025-05-02 17:12:37,298] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:37,307] {logging_mixin.py:115} INFO - [2025-05-02 17:12:37,306] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:12:37,307] {logging_mixin.py:115} INFO - [2025-05-02 17:12:37,307] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:12:37,307] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:12:37,316] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-05-02 17:13:09,389] {processor.py:153} INFO - Started process (PID=8931) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:09,390] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:13:09,391] {logging_mixin.py:115} INFO - [2025-05-02 17:13:09,391] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:09,398] {logging_mixin.py:115} INFO - [2025-05-02 17:13:09,398] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:13:09,398] {logging_mixin.py:115} INFO - [2025-05-02 17:13:09,398] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:13:09,398] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:09,405] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:13:41,373] {processor.py:153} INFO - Started process (PID=9065) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:41,373] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:13:41,373] {logging_mixin.py:115} INFO - [2025-05-02 17:13:41,373] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:41,381] {logging_mixin.py:115} INFO - [2025-05-02 17:13:41,381] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:13:41,381] {logging_mixin.py:115} INFO - [2025-05-02 17:13:41,381] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:13:41,381] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:13:41,388] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:14:13,622] {processor.py:153} INFO - Started process (PID=9204) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:13,623] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:14:13,623] {logging_mixin.py:115} INFO - [2025-05-02 17:14:13,623] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:13,631] {logging_mixin.py:115} INFO - [2025-05-02 17:14:13,631] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:14:13,631] {logging_mixin.py:115} INFO - [2025-05-02 17:14:13,631] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:14:13,631] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:13,639] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:14:46,271] {processor.py:153} INFO - Started process (PID=9340) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:46,271] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:14:46,272] {logging_mixin.py:115} INFO - [2025-05-02 17:14:46,272] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:46,280] {logging_mixin.py:115} INFO - [2025-05-02 17:14:46,279] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:14:46,280] {logging_mixin.py:115} INFO - [2025-05-02 17:14:46,280] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:14:46,280] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:14:46,287] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:15:17,385] {processor.py:153} INFO - Started process (PID=9476) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:17,385] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:15:17,386] {logging_mixin.py:115} INFO - [2025-05-02 17:15:17,386] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:17,396] {logging_mixin.py:115} INFO - [2025-05-02 17:15:17,395] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:15:17,396] {logging_mixin.py:115} INFO - [2025-05-02 17:15:17,396] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:15:17,396] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:17,406] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-05-02 17:15:53,127] {processor.py:153} INFO - Started process (PID=9622) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:53,127] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:15:53,128] {logging_mixin.py:115} INFO - [2025-05-02 17:15:53,128] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:53,135] {logging_mixin.py:115} INFO - [2025-05-02 17:15:53,135] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:15:53,136] {logging_mixin.py:115} INFO - [2025-05-02 17:15:53,135] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:15:53,136] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:15:53,143] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:16:24,946] {processor.py:153} INFO - Started process (PID=9756) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:24,946] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:16:24,947] {logging_mixin.py:115} INFO - [2025-05-02 17:16:24,947] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:24,956] {logging_mixin.py:115} INFO - [2025-05-02 17:16:24,955] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:16:24,956] {logging_mixin.py:115} INFO - [2025-05-02 17:16:24,956] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:16:24,956] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:24,963] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-02 17:16:58,543] {processor.py:153} INFO - Started process (PID=9908) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:58,544] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:16:58,544] {logging_mixin.py:115} INFO - [2025-05-02 17:16:58,544] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:58,552] {logging_mixin.py:115} INFO - [2025-05-02 17:16:58,552] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:16:58,553] {logging_mixin.py:115} INFO - [2025-05-02 17:16:58,552] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:16:58,553] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:16:58,560] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:17:30,126] {processor.py:153} INFO - Started process (PID=10044) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:17:30,127] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:17:30,127] {logging_mixin.py:115} INFO - [2025-05-02 17:17:30,127] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:17:30,136] {logging_mixin.py:115} INFO - [2025-05-02 17:17:30,136] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:17:30,136] {logging_mixin.py:115} INFO - [2025-05-02 17:17:30,136] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:17:30,136] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:17:30,141] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:18:01,173] {processor.py:153} INFO - Started process (PID=10177) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:01,173] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:18:01,174] {logging_mixin.py:115} INFO - [2025-05-02 17:18:01,174] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:01,183] {logging_mixin.py:115} INFO - [2025-05-02 17:18:01,183] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:18:01,183] {logging_mixin.py:115} INFO - [2025-05-02 17:18:01,183] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:18:01,183] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:01,189] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:18:33,101] {processor.py:153} INFO - Started process (PID=10310) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:33,102] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:18:33,103] {logging_mixin.py:115} INFO - [2025-05-02 17:18:33,102] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:33,112] {logging_mixin.py:115} INFO - [2025-05-02 17:18:33,112] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:18:33,112] {logging_mixin.py:115} INFO - [2025-05-02 17:18:33,112] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:18:33,112] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:18:33,118] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:19:09,049] {processor.py:153} INFO - Started process (PID=10465) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:09,049] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:19:09,050] {logging_mixin.py:115} INFO - [2025-05-02 17:19:09,050] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:09,059] {logging_mixin.py:115} INFO - [2025-05-02 17:19:09,059] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:19:09,059] {logging_mixin.py:115} INFO - [2025-05-02 17:19:09,059] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:19:09,059] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:09,065] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:19:39,568] {processor.py:153} INFO - Started process (PID=10594) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:39,568] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:19:39,569] {logging_mixin.py:115} INFO - [2025-05-02 17:19:39,569] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:39,580] {logging_mixin.py:115} INFO - [2025-05-02 17:19:39,579] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:19:39,580] {logging_mixin.py:115} INFO - [2025-05-02 17:19:39,580] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:19:39,580] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:19:39,586] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-02 17:20:12,245] {processor.py:153} INFO - Started process (PID=10732) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:12,246] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:20:12,246] {logging_mixin.py:115} INFO - [2025-05-02 17:20:12,246] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:12,256] {logging_mixin.py:115} INFO - [2025-05-02 17:20:12,255] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:20:12,256] {logging_mixin.py:115} INFO - [2025-05-02 17:20:12,256] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:20:12,256] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:12,262] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:20:44,072] {processor.py:153} INFO - Started process (PID=10877) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:44,072] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:20:44,073] {logging_mixin.py:115} INFO - [2025-05-02 17:20:44,073] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:44,082] {logging_mixin.py:115} INFO - [2025-05-02 17:20:44,082] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:20:44,082] {logging_mixin.py:115} INFO - [2025-05-02 17:20:44,082] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:20:44,082] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:20:44,088] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:21:15,279] {processor.py:153} INFO - Started process (PID=11017) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:15,280] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:21:15,280] {logging_mixin.py:115} INFO - [2025-05-02 17:21:15,280] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:15,293] {logging_mixin.py:115} INFO - [2025-05-02 17:21:15,293] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:21:15,293] {logging_mixin.py:115} INFO - [2025-05-02 17:21:15,293] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:21:15,293] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:15,300] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-05-02 17:21:49,334] {processor.py:153} INFO - Started process (PID=11156) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:49,335] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:21:49,335] {logging_mixin.py:115} INFO - [2025-05-02 17:21:49,335] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:49,346] {logging_mixin.py:115} INFO - [2025-05-02 17:21:49,346] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:21:49,346] {logging_mixin.py:115} INFO - [2025-05-02 17:21:49,346] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:21:49,346] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:21:49,353] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-05-02 17:22:21,194] {processor.py:153} INFO - Started process (PID=11293) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:21,194] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:22:21,194] {logging_mixin.py:115} INFO - [2025-05-02 17:22:21,194] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:21,204] {logging_mixin.py:115} INFO - [2025-05-02 17:22:21,204] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:22:21,204] {logging_mixin.py:115} INFO - [2025-05-02 17:22:21,204] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:22:21,204] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:21,209] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:22:52,703] {processor.py:153} INFO - Started process (PID=11434) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:52,704] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:22:52,705] {logging_mixin.py:115} INFO - [2025-05-02 17:22:52,705] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:52,715] {logging_mixin.py:115} INFO - [2025-05-02 17:22:52,715] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:22:52,716] {logging_mixin.py:115} INFO - [2025-05-02 17:22:52,716] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:22:52,716] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:22:52,722] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-02 17:23:25,379] {processor.py:153} INFO - Started process (PID=11568) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:25,380] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:23:25,380] {logging_mixin.py:115} INFO - [2025-05-02 17:23:25,380] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:25,390] {logging_mixin.py:115} INFO - [2025-05-02 17:23:25,390] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:23:25,390] {logging_mixin.py:115} INFO - [2025-05-02 17:23:25,390] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:23:25,390] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:25,396] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:23:59,226] {processor.py:153} INFO - Started process (PID=11722) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:59,227] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:23:59,227] {logging_mixin.py:115} INFO - [2025-05-02 17:23:59,227] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:59,237] {logging_mixin.py:115} INFO - [2025-05-02 17:23:59,236] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:23:59,237] {logging_mixin.py:115} INFO - [2025-05-02 17:23:59,237] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:23:59,237] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:23:59,242] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:24:30,748] {processor.py:153} INFO - Started process (PID=11854) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:24:30,749] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:24:30,749] {logging_mixin.py:115} INFO - [2025-05-02 17:24:30,749] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:24:30,759] {logging_mixin.py:115} INFO - [2025-05-02 17:24:30,758] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:24:30,759] {logging_mixin.py:115} INFO - [2025-05-02 17:24:30,759] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:24:30,759] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:24:30,764] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:25:03,723] {processor.py:153} INFO - Started process (PID=11993) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:03,724] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:25:03,724] {logging_mixin.py:115} INFO - [2025-05-02 17:25:03,724] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:03,733] {logging_mixin.py:115} INFO - [2025-05-02 17:25:03,733] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:25:03,734] {logging_mixin.py:115} INFO - [2025-05-02 17:25:03,733] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:25:03,734] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:03,739] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:25:36,351] {processor.py:153} INFO - Started process (PID=12132) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:36,352] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:25:36,352] {logging_mixin.py:115} INFO - [2025-05-02 17:25:36,352] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:36,361] {logging_mixin.py:115} INFO - [2025-05-02 17:25:36,361] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:25:36,362] {logging_mixin.py:115} INFO - [2025-05-02 17:25:36,362] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:25:36,362] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:25:36,367] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-05-02 17:26:07,727] {processor.py:153} INFO - Started process (PID=12264) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:07,728] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:26:07,728] {logging_mixin.py:115} INFO - [2025-05-02 17:26:07,728] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:07,739] {logging_mixin.py:115} INFO - [2025-05-02 17:26:07,738] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:26:07,739] {logging_mixin.py:115} INFO - [2025-05-02 17:26:07,739] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:26:07,739] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:07,744] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:26:42,739] {processor.py:153} INFO - Started process (PID=12408) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:42,740] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:26:42,741] {logging_mixin.py:115} INFO - [2025-05-02 17:26:42,741] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:42,751] {logging_mixin.py:115} INFO - [2025-05-02 17:26:42,751] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:26:42,751] {logging_mixin.py:115} INFO - [2025-05-02 17:26:42,751] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:26:42,751] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:26:42,757] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:27:14,142] {processor.py:153} INFO - Started process (PID=12540) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:14,142] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:27:14,143] {logging_mixin.py:115} INFO - [2025-05-02 17:27:14,143] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:14,153] {logging_mixin.py:115} INFO - [2025-05-02 17:27:14,153] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:27:14,153] {logging_mixin.py:115} INFO - [2025-05-02 17:27:14,153] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:27:14,153] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:14,159] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:27:50,097] {processor.py:153} INFO - Started process (PID=12692) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:50,098] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:27:50,098] {logging_mixin.py:115} INFO - [2025-05-02 17:27:50,098] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:50,107] {logging_mixin.py:115} INFO - [2025-05-02 17:27:50,107] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:27:50,107] {logging_mixin.py:115} INFO - [2025-05-02 17:27:50,107] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:27:50,108] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:27:50,113] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-02 17:30:14,261] {processor.py:153} INFO - Started process (PID=13550) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:14,262] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:30:14,262] {logging_mixin.py:115} INFO - [2025-05-02 17:30:14,262] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:14,271] {logging_mixin.py:115} INFO - [2025-05-02 17:30:14,271] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:30:14,271] {logging_mixin.py:115} INFO - [2025-05-02 17:30:14,271] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:30:14,271] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:14,278] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-02 17:30:45,189] {processor.py:153} INFO - Started process (PID=13761) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:45,190] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 17:30:45,190] {logging_mixin.py:115} INFO - [2025-05-02 17:30:45,190] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:45,198] {logging_mixin.py:115} INFO - [2025-05-02 17:30:45,198] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 17:30:45,198] {logging_mixin.py:115} INFO - [2025-05-02 17:30:45,198] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 17:30:45,198] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 17:30:45,207] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-02 20:40:12,974] {processor.py:153} INFO - Started process (PID=516) to work on /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 20:40:12,975] {processor.py:641} INFO - Processing file /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-02 20:40:12,975] {logging_mixin.py:115} INFO - [2025-05-02 20:40:12,975] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 20:40:12,982] {logging_mixin.py:115} INFO - [2025-05-02 20:40:12,982] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-02 20:40:12,982] {logging_mixin.py:115} INFO - [2025-05-02 20:40:12,982] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-02 20:40:12,982] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-02 20:40:12,987] {processor.py:161} INFO - Processing /root/Documents/airflowalu/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
